# Generated by Django 5.1.4 on 2024-12-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bakery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=300)),
                ('item_desciption', models.CharField(max_length=500)),
                ('item_price', models.IntegerField(default=0)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
