# Generated by Django 4.2.20 on 2025-04-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_bakery_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakery',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired (Pending Approval)'), ('deleted', 'Deleted')], default='active', max_length=20),
        ),
    ]
